[package]
name = "websocket-example"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.41.0", features = ["full"]}
tokio-tungstenite = "0.24.0"
futures = "0.3.31"
log = "0.4.22"
env_logger = "0.11.5"